### ISSUE TITLE
Problem with testing on mode 2

### ISSUE THREAD

**Issue by mhmtsarigul** [vislearn/dsacstar#12]
Hello there, 

I have a problem with testing on mode 2. I can train models by using rendered depth maps with mode 2. But when I try to test them it gives results as below. To be sure I tried your pre-trained model it also gives the same results. When I test in mode 1, everything seems correct for both models. 

![image](https://user-images.githubusercontent.com/19689052/134644947-8a961519-6f9c-48dd-a076-4ff4a4d8b1f5.png)

Additionally, in rendered depth maps in seq04 frames between 450-500 does not match with the original images.
![scm_002475](https://user-images.githubusercontent.com/19689052/134646905-c5cb27a6-9de1-4c3e-b0c5-8f435bbaba59.png)
![frame-000475 color](https://user-images.githubusercontent.com/19689052/134646986-6f78afb4-ada5-47fc-93a6-a561e0044d2e.png)

Thanks for sharing your work.

**Comment by ebrach** [comment]
Strange. Did you change the data setup in any way? For example, did you render these depth maps yourself? Or change the file names?

The correspondences between RGB and depth images are established via the file names. My best guess is, that the file name ordering is not consistent. Either because the file names changed, or because in your environment they are somehow read in varying order from disk. Which operating system are you on?

Best,
Eric
