### ISSUE TITLE
mean coordinates of the scene

### ISSUE THREAD

**Issue by sontung** [vislearn/dsacstar#23]
Hello,

I would like to ask about the effects of computing the mean coordinates and applying these means to the final scene map. Because I only see that you applied this step in the initialization phase but not the end-2-end train phase and the test phase. Is it important to perform this step and what was the motivation behind it? Thank you in advance.

**Comment by ebrach** [comment]
Hi,

the mean coordinate is stored in the network after being set in the initialisation phase. That's why we do not have to set it again during e2e training or testing.

I did not ablate the effect of setting the mean coordinate in the final version of the code.The step normalises the coordinate frame for the network and makes initial predictions more meaningful. Imagine the scene center is 100 kilometers away. The network has to predict scene coordinates in the range of hundreds of kilometers which might be difficult to converge to, because the initial reprojection errors will be very large.

That being said, for most datasets, the effect will be small since the center mean is near 0,0,0 anyway.
